# Generated by Django 3.1.1 on 2020-09-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_type', models.CharField(max_length=200)),
                ('movie_review', models.CharField(max_length=200)),
                ('movie_date', models.CharField(max_length=200)),
                ('movie_details', models.CharField(max_length=200)),
            ],
        ),
    ]
