# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-12-14 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MovieReviewApp', '0002_delete_movieinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_type', models.CharField(max_length=200)),
                ('movie_review', models.CharField(max_length=200)),
                ('movie_date', models.CharField(max_length=200)),
                ('movie_details', models.CharField(max_length=200)),
            ],
        ),
    ]
